# companies.py
#
# Auto-built from your spreadsheet.
# Uses each company's careers/jobs link where available, otherwise its homepage.
# To add one later, copy a line and change the name and link.

COMPANIES = [
    {"name": "Neuromagen Pharma",             "url": "https://neuromagen.com"},
    {"name": "Kamada",                        "url": "https://career.kamada.com/Positions"},
    {"name": "OncoHost",                      "url": "https://www.oncohost.com/careers#israel-tab"},
    {"name": "IceCure Medical",               "url": "https://www.icecure-medical.com/company/careers/#positions"},
    {"name": "Dexcel Pharma",                 "url": "https://careers.dexcel.com/"},
    {"name": "Protekt Therapeutics",          "url": "https://protektx.com"},
    {"name": "Compugen",                      "url": "https://cgen.com/careers/default.aspx"},
    {"name": "Regentis Biomaterials",         "url": "https://regentis.co.il"},
    {"name": "NeuroSense Therapeutics",       "url": "https://www.neurosense-tx.com/careers/"},
    {"name": "Orasis Pharmaceuticals",        "url": "https://orasis-pharma.com"},
    {"name": "Prilenia Therapeutics",         "url": "https://jobs.lever.co/prilenia"},
    {"name": "Revium Rx",                     "url": "https://reviumrx.com"},
    {"name": "HT BioImaging",                 "url": "https://htbioimaging.com"},
    {"name": "Alma Therapeutics",             "url": "https://almatherapeutics.com"},
    {"name": "BrainStorm Cell Therapeutics",  "url": "https://brainstorm-cell.com/careers/"},
    {"name": "Gamida Cell",                   "url": "https://www.gamida-cell.com/careers/"},
    {"name": "OPKO Biologics",                "url": "https://opkobiologics.com"},
    {"name": "Nanomedic Technologies",        "url": "https://nanomedic.com/"},
    {"name": "Silexion Therapeutics",         "url": "https://silexion.com/"},
    {"name": "BioLineRx",                     "url": "https://biolinerx.com/careers-and-culture/"},
    {"name": "LGM Pharma",                    "url": "https://lgmpharma.com/"},
    {"name": "OCON Therapeutics",             "url": "https://oconmed.com/"},
    {"name": "Averna Therapeutics",           "url": "https://avernatx.com/careers/"},
    {"name": "Bioforum",                      "url": "https://bioforum.bamboohr.com/careers"},
    {"name": "BiomX",                         "url": "https://biomx.com/"},
    {"name": "Bsense Bio Therapeutics",       "url": "https://bsense-bio.com"},
    {"name": "Enlivex Therapeutics",          "url": "https://enlivex.com/"},
    {"name": "ImPact Biotech",                "url": "https://impactbiotech.com/"},
    {"name": "Kadimastem",                    "url": "https://www.kadimastem.com/careers"},
    {"name": "Mapi Pharma",                   "url": "https://mapi-pharma.com/"},
    {"name": "Matricelf",                     "url": "https://matricelf.com/"},
    {"name": "NanoSynex",                     "url": "https://nanosynex.com/about/"},
    {"name": "Orvida Pharma",                 "url": "https://orvidapharma.com"},
    {"name": "Skip Therapeutics",             "url": "https://skiptx.com"},
    {"name": "Sol-Gel Technologies",          "url": "https://sol-gel.com"},
    {"name": "Vidac Pharma",                  "url": "https://vidacpharma.com/"},
    {"name": "Vyne Therapeutics",             "url": "https://vynetherapeutics.com/careers/"},
    {"name": "Enzymit",                       "url": "https://enzymit.com"},
    {"name": "NewcelX",                       "url": "https://newcelx.com/"},
    {"name": "BioGenCell",                    "url": "https://biogencell.net"},
    {"name": "JaxBio",                        "url": "https://jaxbio.com/"},
    {"name": "Vensica Medical",               "url": "https://vensica.com/#contact"},
    {"name": "Can-Fite BioPharma",            "url": "https://canfite.com"},
    {"name": "Clexio Biosciences",            "url": "https://clexio.com"},
    {"name": "Interna TX",                    "url": "https://interna.bio/"},
    {"name": "Isotopia Molecular Imaging",    "url": "https://isotopia-global.com/careers/"},
    {"name": "PolyPid",                       "url": "https://polypid.com/who-we-are/#careers"},
    {"name": "ImmuneWalk Therapeutics",       "url": "https://immunewalk.com/contact-us#bf786d28-36d5-4e29-855a-2b72090b834d"},
    {"name": "Gamidor Diagnostics",           "url": "https://gamidor.co.il/%d7%a7%d7%a8%d7%99%d7%99%d7%a8%d7%94/"},
    {"name": "Teva",                          "url": "https://tevapharm.com"},
    {"name": "Polyrizon",                     "url": "https://polyrizon-biotech.com/join-our-growing-team/"},
    {"name": "UroGen Pharma",                 "url": "https://www.urogen.com/who-we-are/work-with-us"},
    {"name": "Galmed Pharmaceuticals",        "url": "https://galmedpharma.com/"},
    {"name": "Immunai",                       "url": "https://immunai.com"},
    {"name": "Modulight Bio",                 "url": "https://modulight.bio"},
    {"name": "XTL Biopharmaceuticals",        "url": "https://xtlbio.com/"},
    {"name": "1E Therapeutics",               "url": "https://1etx.com/"},
    {"name": "AID Genomics",                  "url": "https://aidgenomics.com"},
    {"name": "Art Bioscience",                "url": "https://www.artbioscience.com/career"},
    {"name": "CollPlant Biotechnologies",     "url": "https://collplant.com/careers-work-with-us/"},
    {"name": "Curesponse",                    "url": "https://curesponse.com"},
    {"name": "Edity Therapeutics",            "url": "https://edity-tx.com/"},
    {"name": "Emendo Biotherapeutics",        "url": "https://emendobio.com"},
    {"name": "Evogene",                       "url": "https://evogene.com/careers/"},
    {"name": "ImmunoBrain Checkpoint",        "url": "https://immunobrain.com/"},
    {"name": "MetaSight Diagnostics",         "url": "https://metasightdx.com/"},
    {"name": "MyBiotics",                     "url": "https://mybiotics-pharma.com/career/"},
    {"name": "Nanocarry Therapeutics",        "url": "https://nanocarry.com/contact/"},
    {"name": "NeoTX",                         "url": "https://neotx.com/careers/"},
    {"name": "NeuroDerm",                     "url": "https://neuroderm.com/careers/current-openings/"},
    {"name": "Nucleix",                       "url": "https://nucleix.com/contact-us/"},
    {"name": "Promise Bio",                   "url": "https://promise.bio"},
    {"name": "ProPhet Bio",                   "url": "https://pro-phet.com/"},
    {"name": "ProSpec-Tany TechnoGene",       "url": "https://prospecbio.com"},
    {"name": "Purple Biotech",                "url": "https://purple-biotech.com/"},
    {"name": "Renewal Bio",                   "url": "https://renewal.bio"},
    {"name": "Targetgene Biotechnologies",    "url": "https://targetgenebio.com/careers/"},
    {"name": "Biolojic Design",               "url": "https://biolojic.com/job-opportunities/"},
    {"name": "Bee-io Honey",                  "url": "https://bee-io.com/"},
    {"name": "Aleph Farms",                   "url": "https://aleph-farms.com/careers/"},
    {"name": "Sealantium Medical",            "url": "https://sealantium-med.com/"},
    {"name": "Alphabiome",                    "url": "https://alphabiome.ai"},
    {"name": "Aummune",                       "url": "https://aummune.com/"},
    {"name": "Azura Ophthalmics",             "url": "https://azuraophthalmics.com/careers/"},
    {"name": "BioLight",                      "url": "https://bio-light.co.il/"},
    {"name": "Cell Source",                   "url": "https://cell-source.com/"},
    {"name": "Chemomab Therapeutics",         "url": "https://chemomab.com/"},
    {"name": "Coltac Therapeutics",           "url": "https://coltactx.com"},
    {"name": "CytoReason",                    "url": "https://cytoreason.com/career/"},
    {"name": "Eleven Therapeutics",           "url": "https://eleventx.com/careers/"},
    {"name": "Everads Therapy",               "url": "https://everads-therapy.com"},
    {"name": "Gynica",                        "url": "https://gynica.com/"},
    {"name": "Ibex Medical Analytics",        "url": "https://ibex-ai.com/careers/"},
    {"name": "IdentifAI Genetics",            "url": "https://identifai-genetics.com/careers/"},
    {"name": "Imagene AI",                    "url": "https://imagene-ai.com/careers/"},
    {"name": "Levation Pharma",               "url": "https://levationpharma.com/"},
    {"name": "Lutris Pharma",                 "url": "https://lutris-pharma.com"},
    {"name": "Mana.bio",                      "url": "https://www.mana.bio/jobs"},
    {"name": "MNDL Bio",                      "url": "https://mndl.bio"},
    {"name": "Moebius Medical",               "url": "https://www.linkedin.com/company/moebius-medical-ltd-/jobs/"},
    {"name": "Nasus Pharma",                  "url": "https://nasuspharma.com"},
    {"name": "Neurim Pharmaceuticals",        "url": "https://neurim.com/"},
    {"name": "NeuroKaire",                    "url": "https://www.neurokaire.com/careers#Open-Positions"},
    {"name": "Nucleai",                       "url": "https://nucleai.ai/"},
    {"name": "Pangea Biomed",                 "url": "https://pangeabiomed.com/"},
    {"name": "Quris Technologies",            "url": "https://www.quris.ai/careers"},
    {"name": "RedHill Biopharma",             "url": "https://redhillbio.com"},
    {"name": "Scala Biodesign",               "url": "https://www.scala-bio.com/careers"},
    {"name": "Sight Diagnostics",             "url": "https://sightdx.com"},
    {"name": "Syremis Therapeutics",          "url": "https://syremis.com/careers/"},
    {"name": "Twist Bioscience Israel",       "url": "https://twistbioscience.com"},
    {"name": "Ukko",                          "url": "https://ukko.us"},
    {"name": "Unipharm",                      "url": "https://unipharm.global"},
    {"name": "Nano24med",                     "url": "https://nano24med.com/"},
    {"name": "CTNT",                          "url": "https://clinicaltnt.com/"},
    {"name": "Arrakis Bio",                   "url": "https://arrakis.bio"},
    {"name": "Cellergy Therapeutics",         "url": "https://cellergy-bio.com"},
    {"name": "Genopore",                      "url": "https://genopore.com"},
    {"name": "MedAbome",                      "url": "https://medabome.com"},
    {"name": "MediWound",                     "url": "https://mediwound.com/careers/"},
    {"name": "TrojanBio",                     "url": "https://trojan-bio.com"},
    {"name": "Cathetrix",                     "url": "https://www.linkedin.com/company/cathetrix/jobs/"},
    {"name": "Allium Medical",                "url": "https://www.linkedin.com/company/alliumltd/jobs/"},
    {"name": "Epitomee Medical",              "url": "https://www.linkedin.com/company/epitomeemedical/jobs/"},
    {"name": "Itamar Medical",                "url": "https://careers.zoll.com/careers-listing"},
    {"name": "Nitinotes",                     "url": "https://nitinotesurgical.com/"},
    {"name": "OSSIO",                         "url": "https://ossio.io/"},
    {"name": "XACT Robotics",                 "url": "https://xactrobotics.com/"},
    {"name": "BioProtect",                    "url": "https://bioprotect.com/"},
    {"name": "CAPS Medical",                  "url": "https://capsmedical.com"},
    {"name": "Eitan Medical",                 "url": "https://eitanmedical.com/"},
    {"name": "Pulsenmore",                    "url": "https://pulsenmore.com/"},
    {"name": "Append Medical",                "url": "https://appendmedical.com/"},
    {"name": "Exero Medical",                 "url": "https://exeromedical.com/"},
    {"name": "Momentis Surgical",             "url": "https://momentissurgical.com"},
    {"name": "VeinWay",                       "url": "https://veinway.com/"},
    {"name": "BENDIT Technologies",           "url": "https://bendittech.com"},
    {"name": "Biobeat",                       "url": "https://bio-beat.com"},
    {"name": "Nanox",                         "url": "https://nanox.vision"},
    {"name": "Inspira Technologies",          "url": "https://inspira-technologies.com/"},
    {"name": "Lydus Medical",                 "url": "https://lydus-medical.com"},
    {"name": "Medasense Biometrics",          "url": "https://medasense.com/"},
    {"name": "Pi-Cardia",                     "url": "https://pi-cardia.net"},
    {"name": "TechnoPulm",                    "url": "https://t-pulm.com/"},
    {"name": "TechsoMed",                     "url": "https://techsomed.com/"},
    {"name": "DermaDetect",                   "url": "https://dermadetect.com"},
    {"name": "EyeYon Medical",                "url": "https://eye-yon.com/"},
    {"name": "DALI Medical Devices",          "url": "https://dalimed.com"},
]
